# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  pull-requests: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
         path: pr
      - name: Checkout Target of PR
        uses: actions/checkout@v4
        with:
          path: target
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_max_depth: 4
          files: services/**
            
        
      - name: install kustomize
        if: ${{ steps.changed-files.outputs.any_changed }}
        run: |
           curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      - name: Diff each service
        if: ${{ steps.changed-files.outputs.any_changed }}
        env:
          ALL_CHANGED_DIRS: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
           for d in ${ALL_CHANGED_DIRS}; do
             service_name=$(echo $d | cut -d / -f 3)-$(basename ${d})
             kustomize build pr/${d} > ${service_name}-pr.yml
             kustomize build target/${d} > ${service_name}-target.yml
             diff -U 7 ${service_name}-pr.yml ${service_name}-target.yml > ${service_name}-changes.diff || true
           done
      - name: Report changes
        if: ${{ steps.changed-files.outputs.any_changed }}
        env:
          ALL_CHANGED_DIRS: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for d in ${ALL_CHANGED_DIRS}; do
            service_name=$(echo $d | cut -d / -f 3)-$(basename ${d})
            wget https://raw.githubusercontent.com/gruejay/k8s-config-monorepo/test-pr/pr-comment.html
            sed  "s/DESCRIPTION_HERE/${service_name}-Changes/g" pr-comment-template.txt > ${service_name}-diff.txt
            sed  -e "/DIFF_HERE/{r ${service_name}-changes.diff" -e "d}" ${service_name}-diff.txt > ${service_name}-result.txt
          done
          cat *-result.txt > comment.txt
          cat comment.txt
      - name: Add comment to PR
        if: ${{ steps.changed-files.outputs.any_changed }}
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf "%s%s%s" '{ "body" : "' $(cat comment.txt) '" }' > payload.json
          cat payload.json
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '@payload.json'
      - name: Add comment to PR if no changes
        if: ${{ !steps.changed-files.outputs.any_changed }}
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "No changes" }'
